server:
  port: 8080

persistence:
  type: jpa   # your config-driven switch (use "redis" when you swap)

spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:mariadb://localhost:3306/soukconect
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      #ddl-auto: validate   # change to 'update' if you want Hibernate to create/alter tables
      ddl-auto: update   # change to 'update' if you want Hibernate to create/alter tables
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false

# Optional SQL logging while debugging
logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: warn
